version: "3.7"

services:
  web: #backend
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn galeria_project.wsgi -b 0.0.0.0:8000

    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=z!$$4o*1am9w%4*d%b)sx^rjj3(drc^otm17if+03$$#c0y*)ed_
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code/frontend
      # One-way volume to use node_modules from inside image
      - /code/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - web
    command: npm start

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
