version: "3.7"

services:
  backend: #backend
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn galeria_project.wsgi -b 0.0.0.0:8000

    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=bastadeclavessecretas1234
      - DEBUG=1
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
      # One-way volume to use node_modules from inside image
      - /code/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
