# Use an official Python runtime as a parent image
FROM python:3.7

# Install curl, node, & yarn
RUN apt-get -y install curl \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash \
  && apt-get install nodejs \
  && curl -o- -L https://yarnpkg.com/install.sh | bash

WORKDIR /code/

# Install Python dependencies
COPY Pipfile Pipfile.lock /code/backend/
RUN pip install pipenv && pipenv install --system

# Install JS dependencies
WORKDIR /code/frontend

# ./frontend/yarn.lock
COPY ./frontend/package.json ./frontend/yarn.lock /code/frontend/
RUN $HOME/.yarn/bin/yarn install

# Add the rest of the code
COPY . /code/

# Build static files
RUN $HOME/.yarn/bin/yarn build

# Have to move all static files other than index.html to root/
# for whitenoise middleware
WORKDIR /code/frontend/build

RUN mkdir root && mv *.ico *.js *.json root

# Collect static files
# RUN mkdir /app/backend/staticfiles

WORKDIR /code/

# SECRET_KEY is only included here to avoid raising an error when generating static files
RUN  SECRET_KEY=z!$$4o*1am9w%4*d%b)sx^rjj3(drc^otm17if+03$$#c0y*)ed_ \
     python manage.py collectstatic --noinput

EXPOSE $PORT

CMD gunicorn galeria_project.wsgi -b 0.0.0.0:$PORT
