# Generated by Django 3.0.6 on 2020-05-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('author', models.CharField(max_length=444, verbose_name='Nombre')),
                ('description', models.CharField(max_length=444)),
                ('url_web', models.URLField(null=True)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=546)),
                ('url_pic', models.URLField(null=True)),
                ('year', models.CharField(max_length=4)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='galeria_app.Autor')),
            ],
        ),
    ]
