# Generated by Django 3.0.6 on 2020-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
