# Generated by Django 3.0.7 on 2020-06-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='description',
            field=models.CharField(blank=True, max_length=444),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
